#
#
version: '3'
services:
  db:
    image: mdillon/postgis:9.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sos
    # update start-up script to delete not required stuff and set-up sos-database
    volumes:
      - "./sos-init.sql:/docker-entrypoint-initdb.d/zz_sos_init.sql"
      - "./dakamon-sos-db:/var/lib/postgresql/data"
    container_name: db
    networks:
      network:
        ipv4_address: 172.52.0.101
  sos:
    build: .
    image: sos:dakamon
    ports:
      - 8080:8080
      - 8000:8000
    links:
      - db:postgres
    depends_on:
      - db
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
    volumes:
      - "./configuration.db:/usr/local/tomcat/webapps/52n-sos-webapp/configuration.db"
      - "./settings.json:/usr/local/tomcat/webapps/52n-sos-webapp/static/client/helgoland/settings.json"
      - "./application.properties:/usr/local/tomat/webapps/52n-sos-webapp/WEB-INF/classes/application.properties"
    container_name: sos
    command: ["catalina.sh", "jpda", "run"]
    networks:
      network:
        ipv4_address: 172.52.0.102
  shiny:
    image: shiny-server:dakamon
    ports:
      - 3838:3838
    depends_on:
      - db
    links:
      - db:postgres
    container_name: shiny
    networks:
      network:
        ipv4_address: 172.52.0.103
  proxy:
    image: nginx:mainline-alpine
    ports:
      - 80:80
    links:
      - sos:sos
    volumes:
      - "./nginx-proxy.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx-index.html:/usr/share/nginx/html/index.html"
      - "./img:/usr/share/nginx/html/img"
      - "./js:/usr/share/nginx/html/js"
      - "./css:/usr/share/nginx/html/css"
      - "./fonts:/usr/share/nginx/html/fonts"
    container_name: proxy
    networks:
      network:
        ipv4_address: 172.52.0.104
networks:
  network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.52.0.0/24
